version: "3.9"

services:
  postgres:
    build: .
    container_name: pg-container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./all-data:/var/lib/postgresql/data

volumes: {}
